export const IMAGE_PATH = {
  LOGO: '/images/logo.png',
  PEOPLE: '/images/people.png',
  PERSON: '/images/person.png',
  FACULTY: '/images/faculty.png',
  LIBRARY: '/images/library.png',
  ABOUT: '/images/about.png',
  BLACK_LOGO: '/images/black-logo.png',
  SEARCH_POSTFIX: '/images/search-postfix.png',
  DEFAULT_USER_PROFILE: '/images/default-user-profile.png',
  BACKGROUND_IMAGE: '/images/background-image.jpg'
};

export const authenticationType = {
  SET_LOGIN_MODAL_VISIBLE_TOGGLE: 'SET_LOGIN_MODAL_VISIBLE_TOGGLE',
  SET_LOGIN_BUTTON_DISABLE: 'SET_LOGIN_BUTTON_DISABLE',
  SET_LOGIN_VALIDATION_EMAIL: 'SET_LOGIN_VALIDATION_EMAIL',
  SET_LOGIN_VALIDATION_PASSWORD: 'SET_LOGIN_VALIDATION_PASSWORD',
  SET_REGISTER_VALIDATION_USERNAME: 'SET_REGISTER_VALIDATION_USERNAME',
  SET_REGISTER_VALIDATION_EMAIL: 'SET_REGISTER_VALIDATION_EMAIL',
  SET_REGISTER_VALIDATION_PASSWORD: 'SET_REGISTER_VALIDATION_PASSWORD',
  SET_REGISTER_VALIDATION_PASSWORD_CONFIRMATION: 'SET_REGISTER_VALIDATION_PASSWORD_CONFIRMATION'
};